name: Type conversion
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      # Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          repository: codeschooluz/logical_operators_test
          token: ${{secrets.TEST_KEY}}
          path: test
      - name: Install dependencies
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Get list of changed files
        id: changed_files
        run: |
          # Run the git diff-tree command and store the output in a variable
          GITHUB_SHA=${{ github.sha }}
          echo $GITHUB_SHA
          CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r $GITHUB_SHA)
          echo $CHANGED_FILES
          # python3 main.py $CHANGED_FILES
          git diff-tree --no-commit-id --name-only -r $GITHUB_SHA
          
         
