name: Type conversion
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          repository: codeschooluz/logical_operators_test
          token: ${{secrets.TEST_KEY}}
          path: test
      - name: Install dependencies
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Print commit message
        run: |
          echo ${{ github.event.head_commit.message }}
      - name: Print added files
        run: |
          # Iterate over the list of added files
          for file in ${{ github.event.commits.modified }}
          do
            # Print the file path
            echo "Added file: $file"
          done

      - name: Print commit message
        run: |
          echo ${{ github.event.commits }}