name: Type conversion
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          repository: codeschooluz/logical_operators_test
          token: ${{secrets.TEST_KEY}}
          path: test
      - name: Install dependencies
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Print commit message
        run: |
          echo ${{ github.event.head_commit.message }}
      - name: Print changed files
        run: |
          # Iterate over the list of added files
          for file in ${{ github.event.head_commit.added }}
          do
            # Print the file path
            echo "Added file: $file"
          done
          
          # Iterate over the list of modified files
          echo ${{ toJSON(github.event.head_commit.modified) }}
         
          
          # Iterate over the list of removed files
          for file in ${{ github.event.head_commit.removed }}
          do
            # Print the file path
            echo "Removed file: $file"
          done


      # This step will create "an array" of strings, e.g. "path1 path2 path3"
      - name: array
        id: arr
        run: |
          arr=()
          for i in "$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"
          do
            if [[ $i == *"path1"* ]]; then
              arr+=("path1")
            fi
            if [[ $i == *"path2"* ]]; then
              arr+=("path2")
            fi
          done
          echo ::set-output name=arr::${arr[@]}